/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e6e9e7",
        "inverse-primary": "#a1d494",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#6aceff",
        "on-tertiary-fixed-variant": "#004d67",
        "primary-container": "#2d5a27",
        "surface-dim": "#d8dad9",
        "on-primary-container": "#9dd090",
        "outline-variant": "#c2c9bb",
        "on-secondary-fixed": "#2c160e",
        "primary": "#154212",
        "surface": "#f8faf8",
        "surface-container-low": "#f2f4f2",
        "surface-variant": "#e1e3e1",
        "on-primary-fixed": "#002201",
        "primary-fixed": "#bcf0ae",
        "on-primary": "#ffffff",
        "secondary": "#77574d",
        "tertiary-fixed": "#c2e8ff",
        "tertiary": "#003e55",
        "outline": "#72796e",
        "on-secondary-container": "#795950",
        "background": "#f8faf8",
        "inverse-on-surface": "#eff1ef",
        "surface-tint": "#3b6934",
        "inverse-surface": "#2e3130",
        "on-background": "#191c1b",
        "secondary-fixed-dim": "#e7bdb1",
        "on-surface": "#191c1b",
        "on-primary-fixed-variant": "#23501e",
        "surface-container-highest": "#e1e3e1",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#001e2b",
        "tertiary-fixed-dim": "#75d1ff",
        "on-surface-variant": "#42493e",
        "on-secondary-fixed-variant": "#5d4037",
        "surface-container": "#eceeec",
        "primary-fixed-dim": "#a1d494",
        "tertiary-container": "#005775",
        "on-error": "#ffffff",
        "secondary-fixed": "#ffdbd0",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-container": "#fed3c7",
        "surface-bright": "#f8faf8",
        "surface-container-lowest": "#ffffff"
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      spacing: {
        'xl': '32px',
        'margin-desktop': '40px',
        'max-width': '1280px',
        'md': '16px',
        'lg': '24px',
        'gutter': '16px',
        'sm': '12px',
        'base': '8px',
        'xs': '4px',
        'margin-mobile': '16px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      }
    },
  },
  plugins: [],
}